import React, { useState, useRef, useEffect } from 'react';
import { useAttendanceContext } from '../../context/AttendanceContext';
import type { Worker, WorkerOpeningRecord } from '../../types';
import { Modal } from '../common/Modal';
import {
  UserPlus,
  Camera,
  Fingerprint,
  Scan,
  CheckCircle2,
  Upload,
  Sparkles,
  DollarSign,
  Phone,
  CreditCard,
  BadgePercent,
  Check,
  Building2,
  Calendar,
  Clock,
  AlertCircle,
  Utensils,
  BookOpen,
  RotateCcw,
  Wallet,
} from 'lucide-react';

interface CreateOpeningEmployeeModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: (worker: Worker) => void;
}

export const CreateOpeningEmployeeModal: React.FC<CreateOpeningEmployeeModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
}) => {
  const { workers, referrers, addWorker, updateWorkerOpening, sites, sections, currentUser } =
    useAttendanceContext();

  const isAdmin = currentUser?.role === 'admin';

  // Site & Section Selection
  const [selectedSiteId, setSelectedSiteId] = useState<string>(() => {
    return sites[0] ? sites[0].id : '';
  });

  const [selectedSectionId, setSelectedSectionId] = useState<string>(() => {
    const targetSite = sites[0] ? sites[0].id : '';
    const available = sections.filter((s) => s.siteId === targetSite);
    return available[0] ? available[0].id : '';
  });

  useEffect(() => {
    if (isOpen && (!selectedSiteId || !selectedSectionId)) {
      if (sites.length > 0) {
        const firstSiteId = sites[0].id;
        setSelectedSiteId(firstSiteId);
        const siteSecs = sections.filter((s) => s.siteId === firstSiteId);
        if (siteSecs.length > 0) {
          setSelectedSectionId(siteSecs[0].id);
        }
      }
    }
  }, [isOpen, sites, sections, selectedSiteId, selectedSectionId]);

  const handleSiteChange = (siteId: string) => {
    setSelectedSiteId(siteId);
    const siteSecs = sections.filter((s) => s.siteId === siteId);
    if (siteSecs.length > 0) {
      setSelectedSectionId(siteSecs[0].id);
    } else {
      setSelectedSectionId('');
    }
  };

  const activeSite = sites.find((s) => s.id === selectedSiteId);
  const activeSection = sections.find((s) => s.id === selectedSectionId);

  // Serial Number & Employee ID generation (e.g. 01BGM - Ramesh Patel 7890)
  const siteCode = (activeSite?.code || selectedSiteId || 'BGM').trim().toUpperCase();
  const siteWorkers = workers.filter((w) => w.currentSiteId === selectedSiteId);

  let maxSeq = 0;
  siteWorkers.forEach((w) => {
    if (w.serialNumber) {
      const match = w.serialNumber.match(/^(\d+)/);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxSeq) maxSeq = num;
      }
    }
    if (w.id) {
      const match = w.id.match(/^(\d+)/);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxSeq) maxSeq = num;
      }
    }
  });

  const nextSeq = maxSeq > 0 ? maxSeq + 1 : siteWorkers.length + 1;
  const autoGeneratedSerial = `${String(nextSeq).padStart(2, '0')}${siteCode}`;

  // Form State - Personal & Identity
  const [name, setName] = useState('');
  const [mobile, setMobile] = useState('');
  const [aadharNumber, setAadharNumber] = useState('');
  const [address, setAddress] = useState('');
  const [photoUrl, setPhotoUrl] = useState<string | null>(null);

  // Optional custom ID override
  const [isEditingId, setIsEditingId] = useState(false);
  const [customSerial, setCustomSerial] = useState('');
  const [customEmployeeId, setCustomEmployeeId] = useState('');

  const cleanAadhaarDigits = aadharNumber.replace(/\D/g, '');
  const last4Aadhaar = cleanAadhaarDigits.length >= 4 ? cleanAadhaarDigits.slice(-4) : '';

  const activeSerial = customSerial.trim() || autoGeneratedSerial;
  const cleanName = name.trim();
  const previewName = cleanName || 'Ganesh';
  const previewAadhaar = last4Aadhaar || (cleanAadhaarDigits.length > 0 ? cleanAadhaarDigits : '7890');
  const autoGeneratedEmployeeId = `${activeSerial} - ${cleanName || 'Employee'}${last4Aadhaar ? ' ' + last4Aadhaar : ''}`;
  const livePreviewEmployeeId = `${activeSerial} - ${previewName} ${previewAadhaar}`;
  const finalEmployeeId = customEmployeeId.trim() || autoGeneratedEmployeeId;

  // Wage & Employment Type
  const [dailyWage, setDailyWage] = useState('850');
  const [workerType, setWorkerType] = useState<'company' | 'outside'>('company');
  const [referrerId, setReferrerId] = useState('');
  const [commissionRate, setCommissionRate] = useState('50');

  // Biometrics Enrollment
  const [faceEnrolled, setFaceEnrolled] = useState(false);
  const [isEnrollingFace, setIsEnrollingFace] = useState(false);
  const [fingerprintEnrolled, setFingerprintEnrolled] = useState(false);
  const [isEnrollingFingerprint, setIsEnrollingFingerprint] = useState(false);

  // Opening Ledger & Balances (The Core Opening Module)
  const todayStr = new Date().toISOString().split('T')[0];
  const firstOfMonthStr = `${todayStr.slice(0, 7)}-01`;
  const [originalJoiningDate, setOriginalJoiningDate] = useState(todayStr);
  const [asOfDate, setAsOfDate] = useState(firstOfMonthStr);
  const [priorWorkingDays, setPriorWorkingDays] = useState('0');
  const [priorHalfDays, setPriorHalfDays] = useState('0');
  const [priorEarnedWages, setPriorEarnedWages] = useState('0');
  const [isWagesManual, setIsWagesManual] = useState(false);
  const [openingAdvanceBalance, setOpeningAdvanceBalance] = useState('0');
  const [openingPendingWages, setOpeningPendingWages] = useState('0');
  const [openingFoodMeals, setOpeningFoodMeals] = useState('0');
  const [ledgerRemarks, setLedgerRemarks] = useState('');

  // Bank & UPI Details
  const [phonePeNumber, setPhonePeNumber] = useState('');
  const [bankName, setBankName] = useState('');
  const [bankAccountNo, setBankAccountNo] = useState('');
  const [bankIfsc, setBankIfsc] = useState('');
  const [bankHolderName, setBankHolderName] = useState('');

  // General remarks
  const [generalRemarks, setGeneralRemarks] = useState('');
  const [validationError, setValidationError] = useState<string | null>(null);

  // Camera & File refs
  const fileInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const [showLiveCamera, setShowLiveCamera] = useState(false);

  // Sync bank holder name with employee name
  useEffect(() => {
    if (!bankHolderName && name) {
      setBankHolderName(name);
    }
  }, [name, bankHolderName]);

  // Derived Opening Calculations
  const fullDaysNum = Math.max(0, parseFloat(priorWorkingDays) || 0);
  const halfDaysNum = Math.max(0, parseFloat(priorHalfDays) || 0);
  const totalMandays = fullDaysNum + halfDaysNum * 0.5;

  const currentDailyWageNum = Math.max(0, parseFloat(dailyWage) || 0);
  const autoCalculatedWages = Math.round(totalMandays * currentDailyWageNum);

  useEffect(() => {
    if (!isWagesManual) {
      setPriorEarnedWages(String(autoCalculatedWages));
    }
  }, [autoCalculatedWages, isWagesManual]);

  const advanceNum = Math.max(0, parseFloat(openingAdvanceBalance) || 0);
  const pendingWageNum = Math.max(0, parseFloat(openingPendingWages) || 0);
  const netOpeningBalance = pendingWageNum - advanceNum;

  // Camera functions
  const stopCamera = () => {
    if (mediaStreamRef.current) {
      mediaStreamRef.current.getTracks().forEach((track) => track.stop());
      mediaStreamRef.current = null;
    }
    setShowLiveCamera(false);
  };

  const startCamera = async () => {
    try {
      setShowLiveCamera(true);
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'user', width: { ideal: 640 }, height: { ideal: 480 } },
        audio: false,
      });
      mediaStreamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.play();
      }
    } catch {
      setShowLiveCamera(false);
      handleUseDemoPhoto();
    }
  };

  const captureCameraSnapshot = () => {
    if (videoRef.current) {
      const canvas = document.createElement('canvas');
      canvas.width = videoRef.current.videoWidth || 640;
      canvas.height = videoRef.current.videoHeight || 480;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(videoRef.current, 0, 0, canvas.width, canvas.height);
        const dataUrl = canvas.toDataURL('image/jpeg', 0.85);
        setPhotoUrl(dataUrl);
      }
    }
    stopCamera();
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setPhotoUrl(event.target?.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleUseDemoPhoto = () => {
    setPhotoUrl('https://images.unsplash.com/photo-1541888946425-d0fbb186156a?w=400&auto=format&fit=crop&q=80');
  };

  // Biometrics Enrollment Handlers
  const handleEnrollFace = async () => {
    setIsEnrollingFace(true);
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setIsEnrollingFace(false);
    setFaceEnrolled(true);
  };

  const handleEnrollFingerprint = async () => {
    setIsEnrollingFingerprint(true);
    await new Promise((resolve) => setTimeout(resolve, 900));
    setIsEnrollingFingerprint(false);
    setFingerprintEnrolled(true);
  };

  const resetForm = () => {
    setName('');
    setMobile('');
    setAadharNumber('');
    setAddress('');
    setPhotoUrl(null);
    setIsEditingId(false);
    setCustomSerial('');
    setCustomEmployeeId('');
    setDailyWage('850');
    setWorkerType('company');
    setReferrerId('');
    setCommissionRate('50');
    setFaceEnrolled(false);
    setFingerprintEnrolled(false);
    setOriginalJoiningDate(todayStr);
    setAsOfDate(firstOfMonthStr);
    setPriorWorkingDays('0');
    setPriorHalfDays('0');
    setPriorEarnedWages('0');
    setIsWagesManual(false);
    setOpeningAdvanceBalance('0');
    setOpeningPendingWages('0');
    setOpeningFoodMeals('0');
    setLedgerRemarks('');
    setPhonePeNumber('');
    setBankName('');
    setBankAccountNo('');
    setBankIfsc('');
    setBankHolderName('');
    setGeneralRemarks('');
    setValidationError(null);
    stopCamera();
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!isAdmin) {
      setValidationError('Access denied. Only Universal System Admins can create Opening Employees.');
      return;
    }

    if (!name.trim()) {
      setValidationError('Please enter Employee Full Name.');
      return;
    }
    if (!mobile.trim() || mobile.trim().length < 10) {
      setValidationError('Please enter a valid 10-digit mobile number.');
      return;
    }
    if (!selectedSiteId) {
      setValidationError('Please select a project site for this employee.');
      return;
    }
    if (!selectedSectionId) {
      setValidationError('Please select a trade section for this employee.');
      return;
    }
    if (!dailyWage || Number(dailyWage) <= 0) {
      setValidationError('Please specify a valid daily wage rate.');
      return;
    }
    if (!originalJoiningDate) {
      setValidationError('Please enter the Original Historical Joining Date.');
      return;
    }
    if (!asOfDate) {
      setValidationError('Please enter the As-Of Cutover Date.');
      return;
    }

    const serialToSave = customSerial.trim() || autoGeneratedSerial;
    const cleanEmpName = name.trim();
    const finalLast4 = cleanAadhaarDigits.length >= 4 ? cleanAadhaarDigits.slice(-4) : (cleanAadhaarDigits || '');
    const empIdToSave = customEmployeeId.trim() || `${serialToSave} - ${cleanEmpName}${finalLast4 ? ' ' + finalLast4 : ''}`;

    const openingRecord: WorkerOpeningRecord = {
      workerId: empIdToSave,
      originalJoiningDate,
      asOfDate,
      priorWorkingDays: fullDaysNum,
      priorHalfDays: halfDaysNum,
      totalPriorDays: totalMandays,
      priorEarnedWages: Number(priorEarnedWages) || 0,
      openingAdvanceBalance: advanceNum,
      openingPendingWages: pendingWageNum,
      netOpeningBalance,
      openingFoodMeals: Math.max(0, parseInt(openingFoodMeals, 10) || 0),
      remarks: ledgerRemarks.trim() || undefined,
    };

    const newWorkerData: Omit<Worker, 'id'> & { id: string; serialNumber: string; openingRecord: WorkerOpeningRecord } = {
      id: empIdToSave,
      serialNumber: serialToSave,
      name: cleanEmpName,
      mobile: mobile.trim(),
      workerType,
      currentSiteId: selectedSiteId,
      currentSectionId: selectedSectionId,
      joiningDate: originalJoiningDate,
      dailyWage: Number(dailyWage),
      referrerId: referrerId ? referrerId : null,
      commissionType: 'perDay',
      commissionRate: referrerId ? Number(commissionRate) : 0,
      attendanceModes: ['face', 'fingerprint', 'manual'],
      status: 'active',
      idProofNumber: aadharNumber.trim() || undefined,
      address: address.trim() || undefined,
      phonePeNumber: phonePeNumber.trim() || undefined,
      bankName: bankName.trim() || undefined,
      bankAccountNo: bankAccountNo.trim() || undefined,
      bankIfsc: bankIfsc.trim().toUpperCase() || undefined,
      bankHolderName: bankHolderName.trim() || cleanEmpName,
      photoUrl: photoUrl || undefined,
      faceEnrolled,
      fingerprintEnrolled,
      remarks: generalRemarks.trim() || undefined,
      openingRecord,
    };

    const created = addWorker(newWorkerData);
    updateWorkerOpening(created.id, openingRecord);

    if (onSuccess) {
      onSuccess(created);
    }
    resetForm();
    onClose();
  };

  const availableSections = sections.filter((s) => s.siteId === selectedSiteId);

  return (
    <Modal
      isOpen={isOpen}
      onClose={() => {
        stopCamera();
        onClose();
      }}
      title="Admin: Register Opening Employee with Biometrics & Prior Balances"
      size="2xl"
      footer={
        <div className="flex items-center justify-between w-full">
          <div className="text-[11px] text-slate-500 font-medium">
            <span className="font-bold text-slate-700">Auto ID:</span> {finalEmployeeId}
          </div>
          <div className="flex items-center space-x-2">
            <button
              type="button"
              onClick={() => {
                stopCamera();
                onClose();
              }}
              className="px-4 py-2 text-xs font-bold text-slate-600 hover:text-slate-800 hover:bg-slate-100 rounded-xl transition-all cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleSubmit}
              className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white rounded-xl text-xs font-black shadow-md shadow-blue-500/20 transition-all flex items-center space-x-2 active:scale-95 cursor-pointer"
            >
              <CheckCircle2 className="h-4 w-4" />
              <span>Register Opening Employee</span>
            </button>
          </div>
        </div>
      }
    >
      <div className="space-y-6 py-1">
        {/* Error Alert */}
        {validationError && (
          <div className="p-3.5 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-700 font-semibold flex items-center space-x-2">
            <AlertCircle className="h-4 w-4 shrink-0 text-rose-600" />
            <span>{validationError}</span>
          </div>
        )}

        {/* Top Banner: Auto-Generated Serial & Employee ID */}
        <div className="bg-gradient-to-r from-slate-900 via-blue-950 to-indigo-950 text-white p-4 rounded-2xl shadow-sm border border-blue-800/40">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <div className="flex items-center space-x-2 mb-1">
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-purple-500/30 text-purple-200 border border-purple-400/30">
                  Admin Master Onboarding
                </span>
                <span className="text-xs text-blue-200/80 font-medium">
                  Auto-Linked to Site Code ({siteCode})
                </span>
              </div>
              <h2 className="text-xl sm:text-2xl font-black font-mono tracking-tight text-white flex items-center space-x-2">
                <span>{livePreviewEmployeeId}</span>
              </h2>
              <div className="flex flex-wrap items-center gap-2 mt-1.5 text-[11px] text-slate-300">
                <span className="bg-white/10 px-2 py-0.5 rounded font-mono font-bold text-amber-300">
                  Serial No: {activeSerial}
                </span>
                <span>•</span>
                <span className="bg-white/10 px-2 py-0.5 rounded font-bold text-blue-200">
                  Name: {cleanName || 'Ganesh'}
                </span>
                <span>•</span>
                <span className="bg-white/10 px-2 py-0.5 rounded font-mono font-bold text-emerald-300">
                  Aadhaar: {cleanAadhaarDigits ? `...${previewAadhaar}` : '7890 (Sample)'}
                </span>
              </div>
            </div>

            <button
              type="button"
              onClick={() => setIsEditingId(!isEditingId)}
              className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-bold text-white border border-white/20 transition-all flex items-center space-x-1.5 self-start sm:self-center cursor-pointer shrink-0"
            >
              <Sparkles className="h-3.5 w-3.5 text-amber-300" />
              <span>{isEditingId ? 'Close Custom ID' : 'Customize ID / Serial'}</span>
            </button>
          </div>

          {isEditingId && (
            <div className="mt-3 pt-3 border-t border-white/10 grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div>
                <label className="block text-[11px] font-bold text-slate-300 mb-1">
                  Custom Serial Number
                </label>
                <input
                  type="text"
                  placeholder={autoGeneratedSerial}
                  value={customSerial}
                  onChange={(e) => setCustomSerial(e.target.value.toUpperCase())}
                  className="w-full px-3 py-1.5 bg-white/10 border border-white/20 rounded-lg text-xs font-mono font-bold text-white focus:outline-none focus:ring-2 focus:ring-blue-400"
                />
              </div>
              <div>
                <label className="block text-[11px] font-bold text-slate-300 mb-1">
                  Custom Permanent Employee ID
                </label>
                <div className="flex items-center space-x-2">
                  <input
                    type="text"
                    placeholder={autoGeneratedEmployeeId}
                    value={customEmployeeId}
                    onChange={(e) => setCustomEmployeeId(e.target.value)}
                    className="w-full px-3 py-1.5 bg-white/10 border border-white/20 rounded-lg text-xs font-mono font-bold text-white focus:outline-none focus:ring-2 focus:ring-blue-400"
                  />
                  <button
                    type="button"
                    onClick={() => {
                      setCustomSerial('');
                      setCustomEmployeeId('');
                    }}
                    className="px-2.5 py-1.5 bg-rose-500/20 text-rose-200 border border-rose-400/30 rounded-lg text-[11px] font-bold hover:bg-rose-500/30 cursor-pointer flex items-center space-x-1"
                    title="Reset to Auto Generation"
                  >
                    <RotateCcw className="h-3 w-3" />
                    <span>Auto</span>
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* SECTION 1: Site & Section Assignment */}
        <div className="bg-slate-50/80 border border-slate-200/80 rounded-2xl p-4 space-y-3">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <Building2 className="h-4 w-4 text-blue-600" />
            <span>1. Project Site &amp; Trade Section</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Project Site <span className="text-rose-500">*</span>
              </label>
              <select
                value={selectedSiteId}
                onChange={(e) => handleSiteChange(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
              >
                {sites.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name} ({s.code}) - {s.location}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Work Section <span className="text-rose-500">*</span>
              </label>
              <select
                value={selectedSectionId}
                onChange={(e) => setSelectedSectionId(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
              >
                {availableSections.length === 0 && <option value="">No sections in this site</option>}
                {availableSections.map((sec) => (
                  <option key={sec.id} value={sec.id}>
                    {sec.name} ({sec.code}) &bull; Supervisor: {sec.inCharge}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {activeSection && (
            <div className="text-[11px] text-slate-600 pt-2 border-t border-slate-200 flex items-center justify-between">
              <span>
                Site: <strong>{activeSite?.name}</strong> &bull; Section: <strong className="text-blue-700">{activeSection.name}</strong>
              </span>
              <span>Supervisor: <strong>{activeSection.inCharge}</strong> ({activeSection.mobile})</span>
            </div>
          )}
        </div>

        {/* SECTION 2: Personal & Identity Details */}
        <div className="bg-slate-50/80 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <UserPlus className="h-4 w-4 text-blue-600" />
            <span>2. Personal &amp; Identity Details</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Employee Full Name <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                required
                placeholder="e.g. Ganesh Patil"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Phone / Mobile Number <span className="text-rose-500">*</span>
              </label>
              <input
                type="tel"
                required
                maxLength={10}
                placeholder="10-digit mobile number"
                value={mobile}
                onChange={(e) => setMobile(e.target.value.replace(/\D/g, ''))}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Aadhaar Card Number
              </label>
              <input
                type="text"
                maxLength={14}
                placeholder="XXXX XXXX XXXX (e.g. 1234 4567 7890)"
                value={aadharNumber}
                onChange={(e) => {
                  const raw = e.target.value.replace(/\D/g, '').slice(0, 12);
                  const formatted = raw.replace(/(\d{4})(?=\d)/g, '$1 ');
                  setAadharNumber(formatted);
                }}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono"
              />
              <div className="mt-1 flex items-center justify-between text-[11px]">
                <span className="text-slate-500">{cleanAadhaarDigits.length}/12 Digits</span>
                {last4Aadhaar ? (
                  <span className="text-emerald-700 font-bold flex items-center space-x-1 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                    <CheckCircle2 className="h-3 w-3 text-emerald-600" />
                    <span>Last 4: <strong className="font-mono">{last4Aadhaar}</strong> (Auto ID Attached)</span>
                  </span>
                ) : (
                  <span className="text-blue-600">Last 4 digits will attach to Employee ID</span>
                )}
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Home Address / Permanent Location
              </label>
              <input
                type="text"
                placeholder="Village / Town, District, State"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
              />
            </div>
          </div>

          {/* Photo Capture & Upload */}
          <div className="bg-white p-3.5 rounded-xl border border-slate-200 space-y-3">
            <label className="block text-xs font-bold text-slate-800">
              Profile &amp; Gate Face Photo
            </label>

            {showLiveCamera ? (
              <div className="relative rounded-xl overflow-hidden bg-black max-w-sm mx-auto">
                <video ref={videoRef} autoPlay playsInline className="w-full h-48 object-cover" />
                <div className="absolute bottom-2 inset-x-0 flex justify-center space-x-2">
                  <button
                    type="button"
                    onClick={captureCameraSnapshot}
                    className="px-3 py-1.5 bg-blue-600 text-white rounded-lg text-xs font-bold shadow-md cursor-pointer hover:bg-blue-700"
                  >
                    Take Photo
                  </button>
                  <button
                    type="button"
                    onClick={stopCamera}
                    className="px-3 py-1.5 bg-slate-700 text-white rounded-lg text-xs font-bold cursor-pointer hover:bg-slate-800"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex flex-wrap items-center gap-3">
                {photoUrl ? (
                  <div className="relative h-16 w-16 rounded-xl overflow-hidden border-2 border-emerald-500 shadow-sm shrink-0">
                    <img src={photoUrl} alt="Employee" className="h-full w-full object-cover" />
                    <button
                      type="button"
                      onClick={() => setPhotoUrl(null)}
                      className="absolute top-0.5 right-0.5 bg-rose-600 text-white text-[9px] rounded-full h-4 w-4 flex items-center justify-center font-bold"
                    >
                      ×
                    </button>
                  </div>
                ) : (
                  <div className="h-16 w-16 rounded-xl bg-slate-100 border border-dashed border-slate-300 flex items-center justify-center text-slate-400 shrink-0">
                    <Camera className="h-6 w-6" />
                  </div>
                )}

                <div className="flex flex-wrap items-center gap-2">
                  <button
                    type="button"
                    onClick={startCamera}
                    className="px-3 py-1.5 bg-blue-50 text-blue-700 border border-blue-200 hover:bg-blue-100 rounded-xl text-xs font-bold flex items-center space-x-1.5 cursor-pointer active:scale-95"
                  >
                    <Camera className="h-3.5 w-3.5" />
                    <span>Open Camera</span>
                  </button>

                  <input
                    type="file"
                    ref={fileInputRef}
                    accept="image/*"
                    onChange={handleFileUpload}
                    className="hidden"
                  />
                  <button
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="px-3 py-1.5 bg-slate-100 text-slate-700 border border-slate-200 hover:bg-slate-200 rounded-xl text-xs font-bold flex items-center space-x-1.5 cursor-pointer active:scale-95"
                  >
                    <Upload className="h-3.5 w-3.5" />
                    <span>Upload Image</span>
                  </button>

                  <button
                    type="button"
                    onClick={handleUseDemoPhoto}
                    className="px-2.5 py-1.5 text-xs text-slate-500 hover:text-slate-700 underline font-medium cursor-pointer"
                  >
                    Use Sample Photo
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* SECTION 3: Biometrics Registration (Face ID & Optical Fingerprint) */}
        <div className="bg-slate-50/80 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <Scan className="h-4 w-4 text-cyan-600" />
            <span>3. Biometrics Enrolment (Face ID &amp; Fingerprint)</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Face ID Biometrics */}
            <div
              className={`p-4 rounded-xl border transition-all ${
                faceEnrolled ? 'bg-cyan-50/80 border-cyan-300' : 'bg-white border-slate-200'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center space-x-2">
                  <Camera className="h-5 w-5 text-cyan-600" />
                  <span className="text-xs font-bold text-slate-900">Face ID Biometrics</span>
                </div>
                {faceEnrolled && (
                  <span className="text-[10px] font-extrabold text-cyan-700 bg-cyan-100 px-2.5 py-0.5 rounded-full flex items-center space-x-1 border border-cyan-200">
                    <Check className="h-3 w-3" />
                    <span>Enrolled</span>
                  </span>
                )}
              </div>
              <p className="text-[11px] text-slate-500 mb-3">
                Registers 3D facial feature points for contactless gate terminal muster verification.
              </p>
              <button
                type="button"
                onClick={handleEnrollFace}
                disabled={isEnrollingFace}
                className="w-full py-2 bg-cyan-600 hover:bg-cyan-700 text-white rounded-xl text-xs font-bold transition-all flex items-center justify-center space-x-1.5 cursor-pointer active:scale-95 disabled:opacity-50 shadow-xs"
              >
                <Scan className="h-3.5 w-3.5" />
                <span>
                  {isEnrollingFace ? 'Scanning Face Landmarks...' : faceEnrolled ? '✓ Face ID Enrolled (Re-Enroll)' : 'Enroll Face ID'}
                </span>
              </button>
            </div>

            {/* Fingerprint Biometrics */}
            <div
              className={`p-4 rounded-xl border transition-all ${
                fingerprintEnrolled ? 'bg-purple-50/80 border-purple-300' : 'bg-white border-slate-200'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center space-x-2">
                  <Fingerprint className="h-5 w-5 text-purple-600" />
                  <span className="text-xs font-bold text-slate-900">Optical Fingerprint</span>
                </div>
                {fingerprintEnrolled && (
                  <span className="text-[10px] font-extrabold text-purple-700 bg-purple-100 px-2.5 py-0.5 rounded-full flex items-center space-x-1 border border-purple-200">
                    <Check className="h-3 w-3" />
                    <span>Enrolled</span>
                  </span>
                )}
              </div>
              <p className="text-[11px] text-slate-500 mb-3">
                Stores encrypted ridge minutiae for construction site fingerprint sensor terminals.
              </p>
              <button
                type="button"
                onClick={handleEnrollFingerprint}
                disabled={isEnrollingFingerprint}
                className="w-full py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl text-xs font-bold transition-all flex items-center justify-center space-x-1.5 cursor-pointer active:scale-95 disabled:opacity-50 shadow-xs"
              >
                <Fingerprint className="h-3.5 w-3.5" />
                <span>
                  {isEnrollingFingerprint
                    ? 'Scanning Fingerprint Sensor...'
                    : fingerprintEnrolled
                    ? '✓ Fingerprint Enrolled (Re-Scan)'
                    : 'Enroll Fingerprint'}
                </span>
              </button>
            </div>
          </div>
        </div>

        {/* SECTION 4: Daily Wage & Employment Type */}
        <div className="bg-slate-50/80 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <DollarSign className="h-4 w-4 text-emerald-600" />
            <span>4. Wage Rate &amp; Employment Classification</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Daily Wage Rate (₹) <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <span className="absolute left-3 top-2 text-xs font-bold text-slate-400">₹</span>
                <input
                  type="number"
                  required
                  min={100}
                  placeholder="850"
                  value={dailyWage}
                  onChange={(e) => setDailyWage(e.target.value)}
                  className="w-full pl-7 pr-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Employment Type <span className="text-rose-500">*</span>
              </label>
              <select
                value={workerType}
                onChange={(e) => setWorkerType(e.target.value as 'company' | 'outside')}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
              >
                <option value="company">Company Worker (Direct)</option>
                <option value="outside">Outside Worker (Contractor/Agent)</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Reference Employee / Agent
              </label>
              <select
                value={referrerId}
                onChange={(e) => setReferrerId(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
              >
                <option value="">Direct Joining (No Reference)</option>
                {referrers.map((r) => (
                  <option key={r.id} value={r.id}>
                    Agent: {r.name} ({r.mobile})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {referrerId && (
            <div className="bg-purple-50 border border-purple-200 rounded-xl p-3 flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <BadgePercent className="h-4 w-4 text-purple-600" />
                <span className="text-xs font-bold text-purple-900">Referral Commission Rate (₹/day):</span>
              </div>
              <input
                type="number"
                min={0}
                value={commissionRate}
                onChange={(e) => setCommissionRate(e.target.value)}
                className="w-24 px-2 py-1 bg-white border border-purple-300 rounded-lg text-xs font-bold text-purple-900"
              />
            </div>
          )}
        </div>

        {/* SECTION 5: OPENING LEDGER & OLD BALANCES (Requested Core Feature) */}
        <div className="bg-gradient-to-br from-indigo-50/90 via-blue-50/70 to-slate-50 border-2 border-indigo-200/90 rounded-2xl p-4 sm:p-5 space-y-5">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-indigo-100 pb-3">
            <div className="flex items-center space-x-2">
              <span className="p-1.5 bg-indigo-600 text-white rounded-lg">
                <Wallet className="h-4 w-4" />
              </span>
              <div>
                <h3 className="text-sm font-black text-indigo-950 uppercase tracking-wide">
                  5. Opening Balances, Old Advances &amp; Prior Mandays
                </h3>
                <p className="text-[11px] text-indigo-700 font-medium">
                  Enter historical physical ledger balances, original joining date, and prior work days
                </p>
              </div>
            </div>

            {/* Live Net Opening Badge */}
            <div className="self-start sm:self-auto">
              {netOpeningBalance > 0 && (
                <div className="px-3 py-1 rounded-full text-xs font-black bg-emerald-100 text-emerald-900 border border-emerald-300 shadow-xs">
                  Net: +₹{netOpeningBalance.toLocaleString()} (Company Owes Worker &bull; Credit)
                </div>
              )}
              {netOpeningBalance < 0 && (
                <div className="px-3 py-1 rounded-full text-xs font-black bg-rose-100 text-rose-900 border border-rose-300 shadow-xs">
                  Net: -₹{Math.abs(netOpeningBalance).toLocaleString()} (Worker Owes Company &bull; Debit Loan)
                </div>
              )}
              {netOpeningBalance === 0 && (
                <div className="px-3 py-1 rounded-full text-xs font-black bg-slate-200 text-slate-800 border border-slate-300">
                  Net: ₹0 Balanced
                </div>
              )}
            </div>
          </div>

          {/* Joining Date & Cutoff Date */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <label className="block text-xs font-bold text-indigo-950 mb-1 flex items-center space-x-1">
                <Calendar className="h-3.5 w-3.5 text-indigo-600" />
                <span>Original Joining Date (Historical) <span className="text-rose-500">*</span></span>
              </label>
              <input
                type="date"
                required
                value={originalJoiningDate}
                onChange={(e) => setOriginalJoiningDate(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-600"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                The date the worker originally joined before software rollout
              </span>
            </div>

            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <label className="block text-xs font-bold text-indigo-950 mb-1 flex items-center space-x-1">
                <Clock className="h-3.5 w-3.5 text-blue-600" />
                <span>As-Of Cutover Date <span className="text-rose-500">*</span></span>
              </label>
              <input
                type="date"
                required
                value={asOfDate}
                onChange={(e) => setAsOfDate(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-600"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Cutoff date up to which historical ledger data applies
              </span>
            </div>
          </div>

          {/* Prior Working Days & Prior Earned Wages */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <label className="block text-xs font-bold text-indigo-950 mb-1">
                Prior Full Working Days
              </label>
              <input
                type="number"
                min={0}
                value={priorWorkingDays}
                onChange={(e) => setPriorWorkingDays(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-600"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">1.0 Manday per shift</span>
            </div>

            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <label className="block text-xs font-bold text-indigo-950 mb-1">
                Prior Half Working Days
              </label>
              <input
                type="number"
                min={0}
                value={priorHalfDays}
                onChange={(e) => setPriorHalfDays(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-600"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">0.5 Manday per shift</span>
            </div>

            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs font-bold text-indigo-950">Prior Earned Wages (₹)</label>
                <button
                  type="button"
                  onClick={() => setIsWagesManual(!isWagesManual)}
                  className="text-[10px] font-bold text-indigo-600 hover:text-indigo-800 underline cursor-pointer"
                >
                  {isWagesManual ? 'Reset Auto' : 'Manual Edit'}
                </button>
              </div>
              <input
                type="number"
                min={0}
                disabled={!isWagesManual}
                value={priorEarnedWages}
                onChange={(e) => setPriorEarnedWages(e.target.value)}
                className={`w-full px-3 py-1.5 rounded-lg text-xs font-black ${
                  isWagesManual ? 'bg-white border-2 border-indigo-500 text-indigo-950' : 'bg-slate-100 text-slate-700'
                }`}
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Total: <strong>{totalMandays} Mandays</strong> &bull; Auto: ₹{autoCalculatedWages.toLocaleString()}
              </span>
            </div>
          </div>

          {/* Workers Old Amounts: Advances and Pending Wages */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Old Advance Loan Balance (Dr) */}
            <div className="bg-rose-50/70 border border-rose-200 p-3.5 rounded-xl space-y-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-black text-rose-900 uppercase tracking-wide">
                  Old Advance Loan Balance (Dr)
                </label>
                <span className="text-[10px] font-bold px-2 py-0.5 bg-rose-200/80 text-rose-800 rounded">
                  Recoverable Debt
                </span>
              </div>
              <div className="relative">
                <span className="absolute left-3 top-2 text-xs font-bold text-rose-400">₹</span>
                <input
                  type="number"
                  min={0}
                  placeholder="0"
                  value={openingAdvanceBalance}
                  onChange={(e) => setOpeningAdvanceBalance(e.target.value)}
                  className="w-full pl-7 pr-3 py-2 bg-white border border-rose-300 rounded-xl text-xs font-black text-rose-900 focus:outline-none focus:ring-2 focus:ring-rose-500"
                />
              </div>
              <span className="text-[10px] text-rose-700 block">
                Outstanding cash advances carried forward from old physical registers
              </span>
            </div>

            {/* Old Pending / Unpaid Wages (Cr) */}
            <div className="bg-emerald-50/70 border border-emerald-200 p-3.5 rounded-xl space-y-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-black text-emerald-900 uppercase tracking-wide">
                  Old Pending Wages / Opening Amount (Cr)
                </label>
                <span className="text-[10px] font-bold px-2 py-0.5 bg-emerald-200/80 text-emerald-800 rounded">
                  Payable to Worker
                </span>
              </div>
              <div className="relative">
                <span className="absolute left-3 top-2 text-xs font-bold text-emerald-400">₹</span>
                <input
                  type="number"
                  min={0}
                  placeholder="0"
                  value={openingPendingWages}
                  onChange={(e) => setOpeningPendingWages(e.target.value)}
                  className="w-full pl-7 pr-3 py-2 bg-white border border-emerald-300 rounded-xl text-xs font-black text-emerald-900 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                />
              </div>
              <span className="text-[10px] text-emerald-700 block">
                Historical unpaid wages earned prior to cutover date
              </span>
            </div>
          </div>

          {/* Meals & Ledger Remarks */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <label className="block text-xs font-bold text-indigo-950 mb-1 flex items-center space-x-1">
                <Utensils className="h-3.5 w-3.5 text-amber-600" />
                <span>Prior Canteen / Food Meals</span>
              </label>
              <input
                type="number"
                min={0}
                value={openingFoodMeals}
                onChange={(e) => setOpeningFoodMeals(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-600"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Number of subsidized meals consumed before software cutover
              </span>
            </div>

            <div className="bg-white p-3 rounded-xl border border-indigo-100">
              <label className="block text-xs font-bold text-indigo-950 mb-1 flex items-center space-x-1">
                <BookOpen className="h-3.5 w-3.5 text-indigo-600" />
                <span>Physical Ledger Register Reference</span>
              </label>
              <input
                type="text"
                placeholder="e.g. Ledger Vol 2, Page 44, Entry #108"
                value={ledgerRemarks}
                onChange={(e) => setLedgerRemarks(e.target.value)}
                className="w-full px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-600"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Physical binder or book reference number for audit verification
              </span>
            </div>
          </div>
        </div>

        {/* SECTION 6: PhonePe / UPI & Bank Details */}
        <div className="bg-slate-50/80 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <CreditCard className="h-4 w-4 text-indigo-600" />
            <span>6. PhonePe / UPI &amp; Bank Account Details (Optional)</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                PhonePe / GPay / UPI Number
              </label>
              <div className="relative">
                <Phone className="absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-400" />
                <input
                  type="text"
                  placeholder="e.g. 9876543210 or name@upi"
                  value={phonePeNumber}
                  onChange={(e) => setPhonePeNumber(e.target.value)}
                  className="w-full pl-8 pr-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">Bank Name</label>
              <input
                type="text"
                placeholder="e.g. State Bank of India"
                value={bankName}
                onChange={(e) => setBankName(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Bank Account Number
              </label>
              <input
                type="text"
                placeholder="Account number"
                value={bankAccountNo}
                onChange={(e) => setBankAccountNo(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">Bank IFSC Code</label>
              <input
                type="text"
                placeholder="e.g. SBIN0001234"
                value={bankIfsc}
                onChange={(e) => setBankIfsc(e.target.value.toUpperCase())}
                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono uppercase"
              />
            </div>
          </div>
        </div>

        {/* SECTION 7: General Onboarding Remarks */}
        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">
            General Onboarding Remarks &amp; Notes
          </label>
          <input
            type="text"
            placeholder="e.g. Migrated from old register on site transition. Biometrics enrolled at site gate terminal."
            value={generalRemarks}
            onChange={(e) => setGeneralRemarks(e.target.value)}
            className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
          />
        </div>
      </div>
    </Modal>
  );
};
