import React, { useState } from 'react';
import { useAttendanceContext } from '../../context/AttendanceContext';
import { DataTable } from '../../components/common/DataTable';
import type { Column } from '../../components/common/DataTable';
import { FilterBar } from '../../components/common/FilterBar';
import { Select } from '../../components/common/Select';
import { DatePicker } from '../../components/common/DatePicker';
import { StatusBadge } from '../../components/common/StatusBadge';
import { StatCard } from '../../components/common/StatCard';
import { calculateCommission } from '../../utils/calculations/calculateCommission';
import { Coins, UserCheck } from 'lucide-react';

export const Commission: React.FC = () => {
  const { attendance, workers, referrers, assignments, settings, currentUser } = useAttendanceContext();

  // Filters State
  const [filterDate, setFilterDate] = useState(new Date().toISOString().split('T')[0]);
  const [filterReferrer, setFilterReferrer] = useState('');

  // Reset Filters
  const handleReset = () => {
    setFilterDate(new Date().toISOString().split('T')[0]);
    setFilterReferrer('');
  };

  // Compile commission rows
  const commissionLogs = attendance
    .map((record) => {
      const worker = workers.find((w) => w.id === record.workerId);
      const assignment = assignments.find((asg) => asg.id === record.assignmentId);
      const ref = referrers.find((r) => r.id === worker?.referrerId);

      return {
        ...record,
        workerName: worker?.name || 'Unknown',
        workerType: worker?.workerType || 'company',
        referrerId: worker?.referrerId || '',
        referrerName: ref?.name || 'No Referrer',
        commissionType: worker?.commissionType || 'perDay',
        commissionRate: worker?.commissionRate || 0,
        siteId: assignment?.siteId || '',
      };
    })
    .filter((row) => {
      if (row.workerType !== 'outside' || !row.referrerId) return false;
      if (currentUser?.role === 'supervisor' && row.siteId !== currentUser?.assignedSiteId) return false;
      if (filterDate && row.date !== filterDate) return false;
      if (filterReferrer && row.referrerId !== filterReferrer) return false;
      return true;
    });

  // Calculate totals
  const totalCommission = commissionLogs.reduce(
    (sum, row) => sum + calculateCommission(row.status, row.commissionRate, settings),
    0
  );

  const columns: Column<(typeof commissionLogs)[0]>[] = [
    { header: 'S.No', render: (_, idx) => idx + 1 },
    { header: 'Date', accessor: 'date' },
    { header: 'Worker Name', accessor: 'workerName' },
    { header: 'Referrer Agent', accessor: 'referrerName' },
    { header: 'Status', accessor: 'status', render: (row) => <StatusBadge status={row.status} /> },
    {
      header: 'Commission Type',
      accessor: 'commissionType',
      render: (row) => (
        <span className="capitalize text-xs font-semibold px-2 py-0.5 border rounded border-gray-150 bg-gray-50 text-gray-600">
          {row.commissionType === 'perDay' ? 'Per Day' : row.commissionType}
        </span>
      ),
    },
    { header: 'Rate', render: (row) => <span>₹{row.commissionRate}</span> },
    {
      header: 'Commission Earned',
      render: (row) => {
        const amt = calculateCommission(row.status, row.commissionRate, settings);
        return <span className="font-bold text-blue-700">₹{amt}</span>;
      },
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Referrer Commissions</h1>
        <p className="text-sm text-gray-500">Track dynamic commission payments generated by contract workers.</p>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5 max-w-xl">
        <StatCard
          title="Total Commission Earned"
          value={`₹ ${totalCommission}`}
          icon={<Coins className="h-6 w-6 text-blue-600" />}
          description={`Scope: ${filterDate || 'All dates'}`}
        />
        <StatCard
          title="Referred Check-ins"
          value={`${commissionLogs.length} logs`}
          icon={<UserCheck className="h-6 w-6 text-blue-600" />}
          description="Contract worker attendance counts"
        />
      </div>

      {/* Filter Bar */}
      <FilterBar onReset={handleReset}>
        <DatePicker label="Date" value={filterDate} onChange={(e) => setFilterDate(e.target.value)} className="h-9 w-[150px]" />
        <Select
          label="Referrer Agent"
          value={filterReferrer}
          onChange={(e) => setFilterReferrer(e.target.value)}
          options={[{ value: '', label: 'All Agents' }, ...referrers.map((r) => ({ value: r.id, label: r.name }))]}
          className="h-9 w-[180px]"
        />
      </FilterBar>

      <DataTable
        columns={columns}
        data={commissionLogs}
        emptyTitle="No commissions logged"
        emptyDescription="There are no contractor attendance logs registered for this date/referrer."
      />
    </div>
  );
};
export default Commission;
