import React, { useState, useRef, useEffect } from 'react';
import { useAttendanceContext } from '../../context/AttendanceContext';
import type { Section, Site, Worker } from '../../types';
import { Modal } from '../common/Modal';
import {
  UserPlus,
  Camera,
  Fingerprint,
  Scan,
  CheckCircle2,
  Upload,
  Sparkles,
  DollarSign,
  Phone,
  CreditCard,
  BadgePercent,
  Check,
  Building2,
  Briefcase,
} from 'lucide-react';

interface NewEmployeeJoiningModalProps {
  isOpen: boolean;
  onClose: () => void;
  section?: Section | null;
  site?: Site | null;
  initialSiteId?: string;
  initialSectionId?: string;
  onSuccess?: (worker: Worker) => void;
}

export const NewEmployeeJoiningModal: React.FC<NewEmployeeJoiningModalProps> = ({
  isOpen,
  onClose,
  section,
  site,
  initialSiteId,
  initialSectionId,
  onSuccess,
}) => {
  const { workers, referrers, addWorker, sites, sections, currentUser } = useAttendanceContext();

  const isAdmin = currentUser?.role === 'admin';

  // Site and Section selection state (works for both Admin and Supervisor)
  const [selectedSiteId, setSelectedSiteId] = useState<string>(() => {
    return site?.id || section?.siteId || initialSiteId || (sites[0] ? sites[0].id : '');
  });

  const [selectedSectionId, setSelectedSectionId] = useState<string>(() => {
    if (section?.id) return section.id;
    if (initialSectionId) return initialSectionId;
    const targetSite = site?.id || section?.siteId || initialSiteId || (sites[0] ? sites[0].id : '');
    const available = sections.filter((s) => s.siteId === targetSite);
    return available[0] ? available[0].id : (sections[0] ? sections[0].id : '');
  });

  // Sync state if props change
  useEffect(() => {
    if (site?.id) {
      setSelectedSiteId(site.id);
    } else if (section?.siteId) {
      setSelectedSiteId(section.siteId);
    } else if (initialSiteId) {
      setSelectedSiteId(initialSiteId);
    }

    if (section?.id) {
      setSelectedSectionId(section.id);
    } else if (initialSectionId) {
      setSelectedSectionId(initialSectionId);
    }
  }, [site?.id, section?.id, section?.siteId, initialSiteId, initialSectionId]);

  const handleSiteChange = (siteId: string) => {
    setSelectedSiteId(siteId);
    const siteSecs = sections.filter((s) => s.siteId === siteId);
    if (siteSecs.length > 0) {
      setSelectedSectionId(siteSecs[0].id);
    } else {
      setSelectedSectionId('');
    }
  };

  const activeSite = sites.find((s) => s.id === selectedSiteId) || site;
  const activeSection = sections.find((s) => s.id === selectedSectionId) || section;

  // Generated Site-Linked Serial Number (e.g. 01BGM, 02BGM)
  const siteCode = (activeSite?.code || selectedSiteId || 'BGM').trim().toUpperCase();
  const targetSiteId = activeSite?.id || selectedSiteId;
  const siteWorkers = workers.filter((w) => w.currentSiteId === targetSiteId);

  // Compute next sequential 2-digit number for this specific site
  let maxSeq = 0;
  siteWorkers.forEach((w) => {
    if (w.serialNumber) {
      const match = w.serialNumber.match(/^(\d+)/);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxSeq) maxSeq = num;
      }
    }
    if (w.id) {
      const match = w.id.match(/^(\d+)/);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxSeq) maxSeq = num;
      }
    }
  });

  const nextSeq = maxSeq > 0 ? maxSeq + 1 : (siteWorkers.length + 1);
  const autoGeneratedSerial = `${String(nextSeq).padStart(2, '0')}${siteCode}`;

  // Form State - Group 1: Identity & Contact
  const [name, setName] = useState('');
  const [mobile, setMobile] = useState('');
  const [aadharNumber, setAadharNumber] = useState('');
  const [address, setAddress] = useState('');
  const [photoUrl, setPhotoUrl] = useState<string | null>(null);

  // Optional custom override state
  const [isEditingId, setIsEditingId] = useState(false);
  const [customSerial, setCustomSerial] = useState('');
  const [customEmployeeId, setCustomEmployeeId] = useState('');

  // Aadhaar last 4 digits extraction
  const cleanAadhaarDigits = aadharNumber.replace(/\D/g, '');
  const last4Aadhaar = cleanAadhaarDigits.length >= 4 ? cleanAadhaarDigits.slice(-4) : '';

  // Active Serial Number and Employee ID (Format: "01BGM - Ganesh 7890")
  const activeSerial = customSerial.trim() || autoGeneratedSerial;
  const cleanName = name.trim();
  const previewName = cleanName || 'Ganesh';
  const previewAadhaar = last4Aadhaar || (cleanAadhaarDigits.length > 0 ? cleanAadhaarDigits : '7890');
  const autoGeneratedEmployeeId = `${activeSerial} - ${cleanName || 'Employee'}${last4Aadhaar ? ' ' + last4Aadhaar : ''}`;
  const livePreviewEmployeeId = `${activeSerial} - ${previewName} ${previewAadhaar}`;
  const finalEmployeeId = customEmployeeId.trim() || autoGeneratedEmployeeId;

  // Form State - Group 2: Wage & Reference
  const [purpose, setPurpose] = useState('');
  const [dailyWage, setDailyWage] = useState('850');
  const [workerType, setWorkerType] = useState<'company' | 'outside'>('company');
  const [joiningDate, setJoiningDate] = useState(new Date().toISOString().split('T')[0]);
  const [referrerId, setReferrerId] = useState('');
  const [commissionRate, setCommissionRate] = useState('50');

  // Form State - Group 3: PhonePe & Bank Details
  const [phonePeNumber, setPhonePeNumber] = useState('');
  const [bankName, setBankName] = useState('');
  const [bankAccountNo, setBankAccountNo] = useState('');
  const [bankIfsc, setBankIfsc] = useState('');
  const [bankHolderName, setBankHolderName] = useState('');

  // Form State - Group 4: Biometrics Enrollment
  const [faceEnrolled, setFaceEnrolled] = useState(false);
  const [isEnrollingFace, setIsEnrollingFace] = useState(false);
  const [fingerprintEnrolled, setFingerprintEnrolled] = useState(false);
  const [isEnrollingFingerprint, setIsEnrollingFingerprint] = useState(false);

  // Form State - Group 5: Remarks
  const [remarks, setRemarks] = useState('');

  // Camera & File refs
  const fileInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const [showLiveCamera, setShowLiveCamera] = useState(false);

  // Auto-sync bank holder name with employee name if not typed
  useEffect(() => {
    if (!bankHolderName && name) {
      setBankHolderName(name);
    }
  }, [name, bankHolderName]);

  // Clean camera stream on close
  useEffect(() => {
    return () => {
      stopCamera();
    };
  }, [isOpen]);

  const stopCamera = () => {
    if (mediaStreamRef.current) {
      mediaStreamRef.current.getTracks().forEach((track) => track.stop());
      mediaStreamRef.current = null;
    }
    setShowLiveCamera(false);
  };

  const startCamera = async () => {
    try {
      setShowLiveCamera(true);
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'user', width: { ideal: 640 }, height: { ideal: 480 } },
        audio: false,
      });
      mediaStreamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.play();
      }
    } catch {
      setShowLiveCamera(false);
      handleUseDemoPhoto();
    }
  };

  const captureCameraSnapshot = () => {
    if (videoRef.current) {
      const canvas = document.createElement('canvas');
      canvas.width = videoRef.current.videoWidth || 640;
      canvas.height = videoRef.current.videoHeight || 480;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(videoRef.current, 0, 0, canvas.width, canvas.height);
        const dataUrl = canvas.toDataURL('image/jpeg', 0.85);
        setPhotoUrl(dataUrl);
      }
    }
    stopCamera();
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setPhotoUrl(event.target?.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleUseDemoPhoto = () => {
    setPhotoUrl('https://images.unsplash.com/photo-1541888946425-d0fbb186156a?w=400&auto=format&fit=crop&q=80');
  };

  const handleEnrollFace = async () => {
    setIsEnrollingFace(true);
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setIsEnrollingFace(false);
    setFaceEnrolled(true);
  };

  const handleEnrollFingerprint = async () => {
    setIsEnrollingFingerprint(true);
    await new Promise((resolve) => setTimeout(resolve, 900));
    setIsEnrollingFingerprint(false);
    setFingerprintEnrolled(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!name.trim()) {
      alert('Please enter Employee Name.');
      return;
    }
    if (!mobile.trim() || mobile.trim().length < 10) {
      alert('Please enter a valid 10-digit mobile number.');
      return;
    }
    if (!dailyWage || Number(dailyWage) <= 0) {
      alert('Please specify a valid daily wage rate.');
      return;
    }

    if (!selectedSiteId) {
      alert('Please select a project site for this employee.');
      return;
    }
    if (!selectedSectionId) {
      alert('Please select a work section for this employee.');
      return;
    }

    const serialToSave = customSerial.trim() || autoGeneratedSerial;
    const cleanName = name.trim();
    const cleanAadhaar = aadharNumber.replace(/\D/g, '');
    const finalLast4 = cleanAadhaar.length >= 4 ? cleanAadhaar.slice(-4) : (cleanAadhaar || '');
    const empIdToSave = customEmployeeId.trim() || `${serialToSave} - ${cleanName}${finalLast4 ? ' ' + finalLast4 : ''}`;

    const newWorkerData: Omit<Worker, 'id'> & { id: string; serialNumber: string } = {
      id: empIdToSave,
      serialNumber: serialToSave,
      name: cleanName,
      designation: purpose.trim() || undefined,
      purpose: purpose.trim() || undefined,
      mobile: mobile.trim(),
      workerType,
      currentSiteId: selectedSiteId,
      currentSectionId: selectedSectionId,
      joiningDate,
      dailyWage: Number(dailyWage),
      referrerId: referrerId ? referrerId : null,
      commissionType: 'perDay',
      commissionRate: referrerId ? Number(commissionRate) : 0,
      attendanceModes: ['face', 'fingerprint', 'manual'],
      status: 'active',
      idProofNumber: aadharNumber.trim() || undefined,
      address: address.trim() || undefined,
      phonePeNumber: phonePeNumber.trim() || undefined,
      bankName: bankName.trim() || undefined,
      bankAccountNo: bankAccountNo.trim() || undefined,
      bankIfsc: bankIfsc.trim().toUpperCase() || undefined,
      bankHolderName: bankHolderName.trim() || cleanName,
      photoUrl: photoUrl || undefined,
      faceEnrolled,
      fingerprintEnrolled,
      remarks: remarks.trim() || undefined,
    };

    const created = addWorker(newWorkerData);
    if (onSuccess) {
      onSuccess(created);
    }
    onClose();
  };

  const availableSections = sections.filter((s) => s.siteId === selectedSiteId);

  return (
    <>
      <Modal
      isOpen={isOpen}
      onClose={() => {
        stopCamera();
        onClose();
      }}
      title="New Employee Joining Process"
      subtitle={
        isAdmin
          ? `Admin Workforce Enrollment • Deploying to Site: ${activeSite?.name || selectedSiteId} • Section: ${activeSection?.name || selectedSectionId}`
          : `Enrolling directly into Section: ${activeSection?.name || 'Section'} (${activeSection?.code || ''}) • Site: ${activeSite?.name || ''}`
      }
      icon={<UserPlus className="h-5 w-5 text-blue-600" />}
      size="2xl"
    >
      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Top Identity Banner with Auto Serial and Site Code Linked Employee ID */}
        <div className="bg-gradient-to-r from-blue-600 via-indigo-600 to-blue-800 rounded-2xl p-4 text-white shadow-md flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div className="flex-1">
            <div className="flex items-center space-x-2">
              <span className="text-[10px] font-extrabold uppercase tracking-widest text-blue-200 block">
                Official Site-Linked Employee Identity
              </span>
              <span className="text-[10px] font-bold bg-white/20 text-white px-2 py-0.2 rounded-full border border-white/30">
                Site Code: {siteCode}
              </span>
            </div>

            <div className="flex flex-wrap items-center gap-2.5 mt-1.5">
              <span className="font-mono text-xl sm:text-2xl font-black tracking-tight text-white drop-shadow-sm">
                {cleanName ? finalEmployeeId : livePreviewEmployeeId}
              </span>
              <span className="text-xs font-bold bg-emerald-500/30 text-emerald-200 px-2.5 py-0.5 rounded-full border border-emerald-400/40 flex items-center space-x-1">
                <CheckCircle2 className="h-3 w-3 text-emerald-300" />
                <span>Serial: {activeSerial}</span>
              </span>
            </div>

            {/* Formula breakdown tags: Serial + Name + Aadhaar */}
            <div className="flex flex-wrap items-center gap-1.5 mt-2.5 text-[11px]">
              <span className="bg-white/10 px-2 py-0.5 rounded-md border border-white/20 text-blue-100 font-mono">
                Serial No: <strong className="text-white">{activeSerial}</strong>
              </span>
              <span className="text-blue-300 font-bold">+</span>
              <span className="bg-white/10 px-2 py-0.5 rounded-md border border-white/20 text-blue-100">
                Name: <strong className="text-white">{cleanName || 'Ganesh'}</strong>
              </span>
              <span className="text-blue-300 font-bold">+</span>
              <span className="bg-white/10 px-2 py-0.5 rounded-md border border-white/20 text-blue-100">
                Aadhaar Last 4: <strong className="text-white font-mono">{last4Aadhaar || (cleanAadhaarDigits.length > 0 ? cleanAadhaarDigits : '7890')}</strong>
              </span>
            </div>

            <p className="text-xs text-blue-100 mt-2 font-medium">
              Site: <span className="font-semibold">{activeSite?.name || selectedSiteId}</span> (<span className="font-mono font-bold">{siteCode}</span>) • Section: <span className="font-semibold">{activeSection?.name || 'Assigned Section'}</span>
            </p>
          </div>

          <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-xl px-3 py-2 text-right self-stretch sm:self-auto shrink-0">
            <span className="text-[10px] uppercase font-bold text-blue-200 block">Deployment Status</span>
            <span className="text-xs font-extrabold text-white flex items-center justify-end space-x-1 mt-0.5">
              <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse" />
              <span>Direct Active Enrolment</span>
            </span>
            <button
              type="button"
              onClick={() => setIsEditingId(!isEditingId)}
              className="mt-2 text-[10px] underline text-blue-200 hover:text-white font-medium cursor-pointer block text-right w-full"
            >
              {isEditingId ? 'Hide Custom Overrides' : 'Customize ID / Serial'}
            </button>
          </div>
        </div>

        {/* Custom Override Box */}
        {isEditingId && (
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-3.5 space-y-2 text-xs shadow-2xs">
            <div className="font-bold text-amber-900 flex items-center justify-between">
              <span>Manual Serial & Employee ID Override (Advanced)</span>
              <button
                type="button"
                onClick={() => {
                  setCustomSerial('');
                  setCustomEmployeeId('');
                  setIsEditingId(false);
                }}
                className="text-amber-700 underline text-[11px]"
              >
                Reset to Auto
              </button>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] font-bold text-slate-700 mb-1">
                  Site Serial Number
                </label>
                <input
                  type="text"
                  placeholder={autoGeneratedSerial}
                  value={customSerial}
                  onChange={(e) => setCustomSerial(e.target.value)}
                  className="w-full px-3 py-1.5 bg-white border border-amber-300 rounded-xl font-mono text-xs font-bold text-slate-800 focus:ring-2 focus:ring-amber-500 outline-none"
                />
                <span className="text-[10px] text-amber-700 block mt-0.5">
                  Default auto-generated: <strong className="font-mono">{autoGeneratedSerial}</strong>
                </span>
              </div>
              <div>
                <label className="block text-[11px] font-bold text-slate-700 mb-1">
                  Permanent Employee ID
                </label>
                <input
                  type="text"
                  placeholder={autoGeneratedEmployeeId}
                  value={customEmployeeId}
                  onChange={(e) => setCustomEmployeeId(e.target.value)}
                  className="w-full px-3 py-1.5 bg-white border border-amber-300 rounded-xl font-mono text-xs font-bold text-slate-800 focus:ring-2 focus:ring-amber-500 outline-none"
                />
                <span className="text-[10px] text-amber-700 block mt-0.5">
                  Format: <strong className="font-mono">{activeSerial} - {cleanName || 'Ganesh'} {last4Aadhaar || '7890'}</strong>
                </span>
              </div>
            </div>
          </div>
        )}

        {/* SITE & SECTION ASSIGNMENT (For Admin level or when section not pre-locked) */}
        {isAdmin || !section ? (
          <div className="bg-gradient-to-r from-blue-50/90 via-indigo-50/70 to-slate-50 border border-blue-200/90 rounded-2xl p-4 space-y-3 shadow-2xs">
            <div className="flex items-center justify-between">
              <span className="text-xs font-black uppercase tracking-wider text-blue-950 flex items-center space-x-1.5">
                <Building2 className="h-4 w-4 text-blue-600" />
                <span>Project Site &amp; Trade Section Deployment</span>
              </span>
              <span className="text-[10px] bg-blue-100 text-blue-800 font-bold px-2 py-0.5 rounded-full">
                Admin Allocation
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  Deploy to Project Site <span className="text-rose-500">*</span>
                </label>
                <select
                  value={selectedSiteId}
                  onChange={(e) => handleSiteChange(e.target.value)}
                  required
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
                >
                  {sites.map((s) => (
                    <option key={s.id} value={s.id}>
                      {s.name} ({s.code}) &bull; {s.location}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  Assign to Work Section / Trade <span className="text-rose-500">*</span>
                </label>
                <select
                  value={selectedSectionId}
                  onChange={(e) => setSelectedSectionId(e.target.value)}
                  required
                  className="w-full px-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
                >
                  {availableSections.map((sec) => (
                    <option key={sec.id} value={sec.id}>
                      {sec.name} ({sec.code}) &bull; In-Charge: {sec.inCharge}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {activeSection && (
              <div className="flex items-center justify-between text-[11px] text-slate-600 pt-1 border-t border-blue-100">
                <span>Section Supervisor: <strong>{activeSection.inCharge}</strong> ({activeSection.mobile})</span>
                <span className="text-blue-700 font-semibold">{activeSection.remarks || 'Active trade discipline'}</span>
              </div>
            )}
          </div>
        ) : (
          <div className="bg-slate-50 border border-slate-200/80 rounded-2xl p-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
            <div className="flex items-center space-x-2">
              <Building2 className="h-4 w-4 text-blue-600 shrink-0" />
              <span className="text-slate-500">Site:</span>
              <strong className="text-slate-800">{activeSite?.name || section.siteId}</strong>
              <span className="text-slate-300">&bull;</span>
              <span className="text-slate-500">Section:</span>
              <strong className="text-blue-700">{section.name} ({section.code})</strong>
            </div>
            <div className="flex items-center space-x-2.5 self-end sm:self-auto">
              <span className="text-[11px] text-slate-500">Supervisor: {section.inCharge}</span>
            </div>
          </div>
        )}

        {/* SECTION 1: Personal & Identity Details */}
        <div className="bg-slate-50/70 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <UserPlus className="h-4 w-4 text-blue-600" />
            <span>1. Personal & Identity Details</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Employee Name */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Employee Full Name <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                required
                placeholder="e.g. Sanjay Verma"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
              />
            </div>

            {/* Phone Number */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Phone Number <span className="text-rose-500">*</span>
              </label>
              <input
                type="tel"
                required
                maxLength={10}
                placeholder="10-digit mobile number"
                value={mobile}
                onChange={(e) => setMobile(e.target.value.replace(/\D/g, ''))}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono"
              />
            </div>

            {/* Aadhar Number */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Aadhaar Card Number
              </label>
              <input
                type="text"
                maxLength={14}
                placeholder="XXXX XXXX XXXX (e.g. 1234 4567 7890)"
                value={aadharNumber}
                onChange={(e) => {
                  const raw = e.target.value.replace(/\D/g, '').slice(0, 12);
                  const formatted = raw.replace(/(\d{4})(?=\d)/g, '$1 ');
                  setAadharNumber(formatted);
                }}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono"
              />
              <div className="mt-1 flex items-center justify-between text-[11px]">
                <span className="text-slate-500 font-medium">
                  {cleanAadhaarDigits.length}/12 Digits
                </span>
                {last4Aadhaar ? (
                  <span className="text-emerald-700 font-bold flex items-center space-x-1 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                    <CheckCircle2 className="h-3 w-3 text-emerald-600" />
                    <span>Last 4: <strong className="font-mono">{last4Aadhaar}</strong> &bull; Linked to Employee ID</span>
                  </span>
                ) : (
                  <span className="text-blue-600 font-medium">
                    Last 4 digits auto-link to Employee ID (e.g. 7890)
                  </span>
                )}
              </div>
            </div>

            {/* Employee Work Purpose / Role / Designation */}
            <div className="sm:col-span-2">
              <label className="block text-xs font-bold text-slate-700 mb-1 flex items-center justify-between">
                <span className="flex items-center space-x-1">
                  <Briefcase className="h-3.5 w-3.5 text-blue-600 mr-1 inline" />
                  <span>Employee Work Purpose / Role / Designation</span>
                </span>
                <span className="text-[10px] text-blue-600 font-semibold">Auto-updates in Reports</span>
              </label>
              <input
                type="text"
                placeholder="e.g. Senior Mason, Barbender, Carpenter, Tile Layer, Helper, Site Supervisor"
                value={purpose}
                onChange={(e) => setPurpose(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
              />
              <span className="text-[10px] text-slate-400 mt-1 block">
                Official role/purpose will be linked live across daily, weekly, monthly reports, and custom audit slips.
              </span>
            </div>

            {/* Joining Date */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Joining Date <span className="text-rose-500">*</span>
              </label>
              <input
                type="date"
                required
                value={joiningDate}
                onChange={(e) => setJoiningDate(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
              />
            </div>
          </div>

          {/* Address */}
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              Residential / Village Native Address
            </label>
            <input
              type="text"
              placeholder="House/Plot No, Village, Mandal, District, State"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
            />
          </div>

          {/* Employee Photo Upload */}
          <div>
            <label className="block text-xs font-bold text-slate-700 mb-1">
              Employee Photo Profile
            </label>

            {photoUrl ? (
              <div className="flex items-center space-x-4 p-3 bg-white rounded-xl border border-slate-200">
                <div className="h-16 w-16 rounded-xl overflow-hidden bg-slate-900 border border-slate-300 flex-shrink-0">
                  <img src={photoUrl} alt="Employee Preview" className="h-full w-full object-cover" />
                </div>
                <div className="flex-1">
                  <span className="text-xs font-bold text-emerald-700 flex items-center space-x-1">
                    <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                    <span>Photo Attached Successfully</span>
                  </span>
                  <div className="mt-1.5 flex items-center space-x-2">
                    <button
                      type="button"
                      onClick={() => setPhotoUrl(null)}
                      className="px-2.5 py-1 text-[11px] font-bold text-rose-600 bg-rose-50 border border-rose-200 rounded-lg hover:bg-rose-100 transition-colors"
                    >
                      Remove
                    </button>
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      className="px-2.5 py-1 text-[11px] font-semibold text-slate-700 bg-slate-100 rounded-lg hover:bg-slate-200"
                    >
                      Replace
                    </button>
                  </div>
                </div>
              </div>
            ) : showLiveCamera ? (
              <div className="relative rounded-xl overflow-hidden bg-slate-900 border border-slate-800 aspect-video max-h-48 flex flex-col items-center justify-center text-white">
                <video ref={videoRef} className="w-full h-full object-cover" autoPlay playsInline muted />
                <div className="absolute bottom-2 flex items-center space-x-2">
                  <button
                    type="button"
                    onClick={captureCameraSnapshot}
                    className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold flex items-center space-x-1 shadow"
                  >
                    <Camera className="h-4 w-4" />
                    <span>Snap Photo</span>
                  </button>
                  <button
                    type="button"
                    onClick={stopCamera}
                    className="px-3 py-1.5 bg-slate-800 text-slate-300 rounded-lg text-xs font-semibold"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex flex-wrap items-center gap-2.5 p-3 bg-white rounded-xl border border-slate-200">
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200 rounded-xl text-xs font-bold flex items-center space-x-1.5 cursor-pointer"
                >
                  <Upload className="h-3.5 w-3.5" />
                  <span>Upload Photo</span>
                </button>
                <button
                  type="button"
                  onClick={startCamera}
                  className="px-3 py-1.5 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold flex items-center space-x-1.5 cursor-pointer"
                >
                  <Camera className="h-3.5 w-3.5 text-cyan-400" />
                  <span>Take Live Photo</span>
                </button>
                <button
                  type="button"
                  onClick={handleUseDemoPhoto}
                  className="px-3 py-1.5 bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200 rounded-xl text-xs font-semibold flex items-center space-x-1 cursor-pointer"
                >
                  <Sparkles className="h-3.5 w-3.5 text-amber-500" />
                  <span>Use Demo Photo</span>
                </button>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleFileUpload}
                  className="hidden"
                />
              </div>
            )}
          </div>
        </div>

        {/* SECTION 2: Wage, Worker Type & Reference Employee */}
        <div className="bg-slate-50/70 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <DollarSign className="h-4 w-4 text-emerald-600" />
            <span>2. Wage & Reference Employee (Commission)</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {/* Daily Wage / Per Day Amount */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Per Day Amount (Wage) <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <span className="absolute left-3 top-2 text-xs font-bold text-slate-400">₹</span>
                <input
                  type="number"
                  required
                  min={100}
                  placeholder="850"
                  value={dailyWage}
                  onChange={(e) => setDailyWage(e.target.value)}
                  className="w-full pl-7 pr-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600"
                />
              </div>
            </div>

            {/* Employment Type */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Employment Type <span className="text-rose-500">*</span>
              </label>
              <select
                value={workerType}
                onChange={(e) => setWorkerType(e.target.value as 'company' | 'outside')}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
              >
                <option value="company">Company Worker (Direct Roster)</option>
                <option value="outside">Outside Worker (Agent/Contractor)</option>
              </select>
            </div>

            {/* Reference Employee Name in Dropdown */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Reference Employee / Agent (Dropdown)
              </label>
              <select
                value={referrerId}
                onChange={(e) => setReferrerId(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 cursor-pointer"
              >
                <option value="">Direct Joining (No Reference)</option>
                <optgroup label="Registered Agents / Referrers">
                  {referrers.map((r) => (
                    <option key={r.id} value={r.id}>
                      {r.name} ({r.mobile})
                    </option>
                  ))}
                </optgroup>
                <optgroup label="Existing Senior Workers as References">
                  {workers.slice(0, 8).map((w) => (
                    <option key={w.id} value={w.id}>
                      {w.name} - ID {w.id} ({w.mobile})
                    </option>
                  ))}
                </optgroup>
              </select>
            </div>
          </div>

          {/* If Referrer selected, show Commission Per Day */}
          {referrerId && (
            <div className="bg-purple-50/70 border border-purple-200/80 rounded-xl p-3 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center space-x-2">
                <BadgePercent className="h-4 w-4 text-purple-600 flex-shrink-0" />
                <div>
                  <span className="text-xs font-bold text-purple-900 block">
                    Referral Commission Enabled
                  </span>
                  <span className="text-[11px] text-purple-700">
                    Payable to selected reference employee on active attendance
                  </span>
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <label className="text-xs font-bold text-purple-900 whitespace-nowrap">Commission Per Day:</label>
                <div className="relative w-28">
                  <span className="absolute left-2.5 top-1.5 text-xs font-bold text-purple-400">₹</span>
                  <input
                    type="number"
                    min={0}
                    value={commissionRate}
                    onChange={(e) => setCommissionRate(e.target.value)}
                    className="w-full pl-6 pr-2 py-1 bg-white border border-purple-200 rounded-lg text-xs font-bold text-purple-900 focus:outline-none focus:ring-2 focus:ring-purple-600"
                  />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* SECTION 3: PhonePe / UPI & Bank Details */}
        <div className="bg-slate-50/70 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <CreditCard className="h-4 w-4 text-indigo-600" />
            <span>3. PhonePe / UPI & Bank Details</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* PhonePe / UPI Number */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                PhonePe / GPay / UPI Number
              </label>
              <div className="relative">
                <Phone className="absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-400" />
                <input
                  type="text"
                  placeholder="e.g. 9876543210 or name@upi"
                  value={phonePeNumber}
                  onChange={(e) => setPhonePeNumber(e.target.value)}
                  className="w-full pl-8 pr-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
                />
              </div>
            </div>

            {/* Bank Name */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Bank Name
              </label>
              <input
                type="text"
                placeholder="e.g. State Bank of India / HDFC Bank"
                value={bankName}
                onChange={(e) => setBankName(e.target.value)}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600"
              />
            </div>

            {/* Bank Account Number */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Bank Account Number
              </label>
              <input
                type="text"
                placeholder="e.g. 34891029384"
                value={bankAccountNo}
                onChange={(e) => setBankAccountNo(e.target.value.replace(/\D/g, ''))}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono"
              />
            </div>

            {/* IFSC Code */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Bank IFSC Code
              </label>
              <input
                type="text"
                maxLength={11}
                placeholder="e.g. SBIN0001234"
                value={bankIfsc}
                onChange={(e) => setBankIfsc(e.target.value.toUpperCase())}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs font-semibold text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 font-mono uppercase"
              />
            </div>
          </div>
        </div>

        {/* SECTION 4: Biometric Registration (Face ID & Fingerprint) */}
        <div className="bg-slate-50/70 border border-slate-200/80 rounded-2xl p-4 space-y-4">
          <div className="flex items-center space-x-2 text-xs font-black text-slate-800 uppercase tracking-wider">
            <Scan className="h-4 w-4 text-cyan-600" />
            <span>4. Biometrics Enrolment (Face ID & Fingerprint)</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Face ID Box */}
            <div className={`p-4 rounded-xl border transition-all ${faceEnrolled ? 'bg-cyan-50/80 border-cyan-300' : 'bg-white border-slate-200'}`}>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center space-x-2">
                  <Camera className="h-5 w-5 text-cyan-600" />
                  <span className="text-xs font-bold text-slate-900">Face ID Biometrics</span>
                </div>
                {faceEnrolled && (
                  <span className="text-[10px] font-extrabold text-cyan-700 bg-cyan-100 px-2 py-0.5 rounded-full flex items-center space-x-1">
                    <Check className="h-3 w-3" />
                    <span>Enrolled</span>
                  </span>
                )}
              </div>
              <p className="text-[11px] text-slate-500 mb-3">
                Captures 3D facial landmarks for contactless check-in at construction gate terminals.
              </p>
              <button
                type="button"
                onClick={handleEnrollFace}
                disabled={isEnrollingFace}
                className="w-full py-2 bg-cyan-600 hover:bg-cyan-700 text-white rounded-xl text-xs font-bold transition-all flex items-center justify-center space-x-1.5 cursor-pointer active:scale-95 disabled:opacity-50 shadow-xs"
              >
                <Scan className="h-3.5 w-3.5" />
                <span>{isEnrollingFace ? 'Scanning Face...' : faceEnrolled ? 'Re-Enroll Face ID' : 'Enroll Face ID'}</span>
              </button>
            </div>

            {/* Fingerprint Box */}
            <div className={`p-4 rounded-xl border transition-all ${fingerprintEnrolled ? 'bg-purple-50/80 border-purple-300' : 'bg-white border-slate-200'}`}>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center space-x-2">
                  <Fingerprint className="h-5 w-5 text-purple-600" />
                  <span className="text-xs font-bold text-slate-900">Optical Fingerprint</span>
                </div>
                {fingerprintEnrolled && (
                  <span className="text-[10px] font-extrabold text-purple-700 bg-purple-100 px-2 py-0.5 rounded-full flex items-center space-x-1">
                    <Check className="h-3 w-3" />
                    <span>Enrolled</span>
                  </span>
                )}
              </div>
              <p className="text-[11px] text-slate-500 mb-3">
                Registers high-resolution ridge pattern for heavy-duty field biometric scanner devices.
              </p>
              <button
                type="button"
                onClick={handleEnrollFingerprint}
                disabled={isEnrollingFingerprint}
                className="w-full py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl text-xs font-bold transition-all flex items-center justify-center space-x-1.5 cursor-pointer active:scale-95 disabled:opacity-50 shadow-xs"
              >
                <Fingerprint className="h-3.5 w-3.5" />
                <span>{isEnrollingFingerprint ? 'Scanning Finger...' : fingerprintEnrolled ? 'Re-Enroll Fingerprint' : 'Enroll Fingerprint'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* SECTION 5: Remarks & Notes */}
        <div>
          <label className="block text-xs font-bold text-slate-700 mb-1">
            Supervisor Scope & Onboarding Remarks
          </label>
          <input
            type="text"
            placeholder="e.g. Excavator operator and trenching specialist. Safety boots and helmet issued on joining."
            value={remarks}
            onChange={(e) => setRemarks(e.target.value)}
            className="w-full px-3 py-2 bg-white border border-slate-200 rounded-xl text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-600 placeholder:text-slate-400"
          />
        </div>

        {/* Submit Actions */}
        <div className="flex items-center justify-between pt-4 border-t border-slate-200">
          <div className="text-xs text-slate-500 font-medium">
            Employee ID: <span className="font-mono font-bold text-blue-700">{cleanName ? finalEmployeeId : `${activeSerial} - ...`}</span> &bull; Serial: <span className="font-mono font-bold text-slate-800">{activeSerial}</span> in <span className="font-semibold text-slate-800">{activeSection?.name || 'Selected Section'}</span>
          </div>

          <div className="flex items-center space-x-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 rounded-xl transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold shadow-md shadow-blue-600/25 transition-all active:scale-95 flex items-center space-x-2 cursor-pointer"
            >
              <CheckCircle2 className="h-4 w-4" />
              <span>Register & Onboard Employee</span>
            </button>
          </div>
        </div>
      </form>
    </Modal>
  </>
  );
};
